// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vakhpfvatoikjkhtxatd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZha2hwZnZhdG9pa2praHR4YXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MTAwNDcsImV4cCI6MjA2NzE4NjA0N30.Ei1b1CYgbrNQr0tvkmgv6inlo3ohOPsYNIedra7TPoM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});